### PR TITLE
Create pythonapp.yml

### PR DESCRIPTION
**Pull request by timmy61109**

### CODE REVIEW

**Comment by timmy61109** [comment]
If yes, is it possible to provide a .aia file for me to use Pytest for testing in CI, and I can go to the testing process better.

**Comment by timmy61109** [comment]
In fact, it is not so difficult to operate this. You can see that the results of using the same packages Pylint, Flake8 and Pytest are all the same as online. In other words, in general, you must develop the habit of maintaining the code style and conform to Normative practice, so that it will not always be wrong.

The first picture works on my computer, the second chapter picture works on GitHub, with the same error message.

image

image

Original URL of the error message in Chapter 2:[timmy61109 AI-Kit runs 380848785](https://github.com/timmy61109/AI-Kit/runs/380848785)

If yes, is it possible to provide a .aia file for me to use Pytest for testing in CI, and I can go to the testing process better.

Of course, at the same time, it can be used with a text editor kit, which can reduce the time that Code has to check as shown in the following figure.

image

**Comment by ysfchn** [comment]
Thanks for your contribution! I'm actually beginner to Python, so code is not perfect. 😅 Looks like it is better to not throw an error when executing the app without aia file. I'm still learning. 😬 Of course let me give an aia file which is corrupted and not cleaned yet.

[sample.zip](https://github.com/ysfchn/AI-Kit/files/4039132/sample.zip)

Let me know if you done, otherwise I will merge the PR.

**Comment by timmy61109** [comment]
Thank you for providing me the test file.

I just learned a relatively long time but not specialization, and today I also know that the use of requirements.txt.

**Comment by timmy61109** [comment]
Can you help me confirm that this file has been processed well?
Can you tell me what to do with the file?

[devrim.zip](https://github.com/ysfchn/AI-Kit/files/4039982/devrim.zip)

**Comment by timmy61109** [comment]
@ysfchn This is the final execution result [381113987](https://github.com/timmy61109/AI-Kit/runs/381113987). You can continue to use this development through all passes. If you encounter problems, you can mark me and let me take a look.

Now please enjoy the set CI, and the test can work normally, you can see the results of [381192775](https://github.com/timmy61109/AI-Kit/runs/381192775), even the instructions are tested.

**Comment by ysfchn** [comment]
@timmy61109 Thank you so much!

Results are good as expected, all of them are working great, and file is processed well!

AIA files are source files of projects which is used for an non-code mobile app development platform called [MIT App Inventor](https://appinventor.mit.edu/). This app just fixes the corrupted projects, and cleans the unused assets in a project. So they can be imported back again to the platform. 

AIA files are actually an compressed archive, so you will see the contents if you try to open the .aia file with an archive opener such as 7Zip, WinRAR etc.

Now let me merge your pull request, thank you again for your help! 😁

**Review by ysfchn — APPROVED** [review]

**Comment by timmy61109** [comment]
Thank you for your explanation. I think your program can be more streamlined. I believe it can help you make the program more perfect afterwards.

**Comment by ysfchn** [comment]
Thank you for kind words, yeah it can be streamlined, as it is a new repository, there is a lot of work to do 😁

**Pull request merged**
